theme: jekyll-theme-slate
permalink: /:year/:month/:title:output_ext
title: Lance England
description: Data + Analysis + Integration + Automation
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-feed
  - jekyll-sitemap